export const TOGGLE_SEARCHING_STATUS = 'TOGGLE_SEARCHING_STATUS';
export const SAVE_FETCHED_MOVIES = 'SAVE_FETCHED_MOVIES';
export const SAVE_SIMILAR_MOVIES = 'SAVE_SIMILAR_MOVIES';

export const SAVE_AUTHENTICATED_USER = 'SAVE_AUTHENTICATED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
